apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
      - name: shoppingapi
        image: sharadit/devops-shoppingapi:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: DatabaseSettings__ConnectionString
            value: mongodb://username:password@mongo-service:27017
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
spec:
  type: LoadBalancer
  selector:
    app: shoppingapi
  ports:
  - protocol: TCP
    port: 5000   
            
