apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient-deployment 
  labels:
    app: shoppingclient  
spec:
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
      - name: shoppingclient
        image: sharadit/devops-shoppingclient:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ShoppingAPIUrl
            value: http://shoppingapi-service:5000

---
apiVersion: v1
kind: Service
metadata:
  name: shoppingclient-svc
spec:
  type: LoadBalancer
  selector:
    app: shoppingclient
  ports:
  - port: 5001
    protocol: TCP
